@startuml XerbutriComponent
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
LAYOUT_WITH_LEGEND()

title 3. Component diagram for Xerbutri
AddRelTag("link", $textColor="blue", $lineColor="blue", $lineStyle = DashedLine())

Container_Boundary(xerbutri, "TX App", "Container: JavaScript", ""){
	Component(app, "Main - index", "Vite-JavaScript - HTML", "App starting point")
    Component(index, "Index page", "JavaScript - HTML", "Page with the blogs indexed")
    Component(blog, "Blog", "JavaScript - HTML", "Page with the (object) blog and gallery")
    Component(map, "Map", "JavaScript - HTML", "Page with all objects on a map")
    Component(translator, "Translator", "JavaScript", "Provides translations")
}

Container_Boundary(data, "Persistance system", "Container: filesystem", "Using the filesystem for persistance"){
    Component(homedata, "index.{lang}.json", "JSON", "Files with data for the homepage")
    Component(transdata, "{lang}.json", "JSON", "Files with translations data")
    Component(blogstransdata, "blog.{lang}.json", "JSON", "Files with data for the blogpage (get category for path, set title")
    Component(blogidtransdata, "{cat}/{bid}/blog.{lang}.json", "JSON", "Files with translated data for the blogpage")
    Component(blogtransdata, "{cat}/{bid}/blog.json", "JSON", "Files with language independent data for the blogpage")
    Component(imagedata, "{cat}/{bid}/items.json", "JSON", "Files with language independent data for the gallery")
    'Component(mapdata, "Some map file", "JSON", "File with data for the map")
}


'Rel(xerbutri, data, "gets content")
Rel(app, index, "State Machine Router")
Rel(app, map, "State Machine Router")
Rel(app, blog, "State Machine Router")

Rel_U(translator, blog, "sets translations")
Rel_U(translator, index, "sets translations")
Rel_U(transdata, translator, "gets translations")
'Rel(translator, map, "sets translations")


Rel_D(index, homedata, "gets content")
Rel_D(blog, blogstransdata, "1. get category for path\n2. set title")
Rel_D(blog, blogidtransdata, "Article content")
Rel_D(blog, blogtransdata, "Facts dates etc")
Rel_D(blog, imagedata, "Gallery content")

'Rel(map, mapdata, "gets content")

Rel(index, blog, "contains links to blogs", $tags="link")
Rel(index, map, "contains links to map", $tags="link")
'Rel(map, blog, "contains links to blogs", $tags="link")
'Rel(blog, blog, "contains links to blogs", $tags="link")

@enduml