# Sample workflow for continuous integration for a VitePress site

name: CI

on:
  workflow_call:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm install
      - name: Build
        run: npm run build